### PR TITLE
accept file object.

### PR DESCRIPTION
**Pull request by hamano**
mailparser.parse_from_file() should accept file object.

It should be the same as email.message_from_file().

Currently we can't handle mail from standard input.

### CODE REVIEW

**Comment by fedelemantuano** [comment]
What do you want to do? I could use a file object as input (like `email `library), but I can't undestand how you can use mailparse with stdin without `sys.stdin`.

**Comment by hamano** [comment]
I want to parse with sys.stdin:
~~~
mail = mailparser.parse_from_file(sys.stdin)
~~~

I don't want to parse with string:
~~~
mail = mailparser.parse_from_string(sys.stdin.read())
~~~

It's necessary to use more memory.
Thank you!

**Comment by fedelemantuano** [comment]
I cannot use that function to parse stdin, because I use it for outlook messages and I need to give backward compatibility. So I'm going to develop a new function.

**Comment by hamano** [comment]
My patch keeps compatibility.
parse_from_file() accept both filename and stream.
Thanks.

**Comment by fedelemantuano** [comment]
I read your code, but it fails the unittest and then outlook mail can be parse only from file path. So the better way for me is change function.

**Comment by fedelemantuano** [comment]
Hi @hamano, I added your request in [this commit](https://github.com/SpamScope/mail-parser/commit/cdd619fcee55bee75ced1e2aaf2ad676cad7227b). Thanks a lot for suggestion.

**Comment by hamano** [comment]
many thanks!

**Pull request closed without merging**
