### PR TITLE
[WIP] Add tests for receiveds_parsing

### PR DESCRIPTION
**Pull request by ad-m**
I create this pull requests to define and facilitate the introduction of the desired function for me.

I am asking to take action to introduce the "for" parsing in the "Received" header, in addition to the previous ones. In the published pull request, I give an example of a header and result.

Unfortunately, the regular expression in the library is too complex for me to change it myself.

### CODE REVIEW

**Comment by fedelemantuano** [comment]
The parsing of received is very difficult and not cover all cases (but almost all).

When the parsing works the output is:

```
  {
  "date": "Mon, 20 Aug 2018 07:21:19 +0000 UTC",
  "by": "localhost Server",
  "with": "ESMTP id 70F6E3D1EB5 for <wester@test.com>",
  "delay": 0,
  "from": "fake.com unknown 121.0.40.84",
  "date_utc": "2018-08-20T07:21:19",
  "hop": 1
}
```
But as fallback has the raw received.

I can refine the original regex to include others cases.
Is it good for you?

**Comment by ad-m** [comment]
I can see what values are available. In my test, I used the parsed data and added a new field ```for```. I am interested in the easiest possible access from the e-mail address available in field ```for``` in ```Received``` headers.

My use case is I wrote an application using our library that deals with sending e-mails to a webhook ( https://github.com/watchdogpolska/imap-to-webhook ). In web application it is typical to send e-mail using unique e-mail address and match responses using that unique e-mail address (GitHub do it this way), because eq. e-mail address contains ```threadId``` encoded. Sometimes the address to which the message was delivered is not visible in the basic headers of the message, because it is an element of the command ```RCP TO``` in SMTP protocol, which is used, for example, in blink carbon copy ( https://en.wikipedia.org/wiki/Blind_carbon_copy ). I want to collect this kind of potential delivery email addresses from the headlines in my library. Other servers use the ```Envelope-Do``` headers, ```Delivered-To```. Now I deal with the server that the RCP TO address places in the ```Relivered.for``` header.

**Comment by fedelemantuano** [comment]
Can attach me an example of raw mail with this `for` part?

**Comment by fedelemantuano** [comment]
Don't worry I checked on my mails. When there is `for` header in received, mail-parser fails parsing and give you raw header:

```
{
  "raw": "from [::1] (port=40110 helo=uksrv1.fake.com)\n\tby uksrv1.fake.com with esmtpa (Exim 4.91)\n\t(envelope-from <info@fake.ga>)\n\tid 1frpkI-00AEss-Kq; Mon, 20 Aug 2018 20:21:46 +0100",
  "hop": 1
},
{
  "raw": "from uksrv1.fake.com (uksrv1.fake.com [142.93.122.21])\n\tby localhost (Qmail) with ESMTP id EC2893R1E97\n\tfor <bichitra@wawawa.com>; Mon, 20 Aug 2018 19:29:03 +0000 (UTC)",
  "hop": 2
}
```

I can work on it.

**Comment by ad-m** [comment]
@fedelemantuano , i think in pull request I publish example headers. There is not only new issue, but new pull request also. There is raw email too https://github.com/watchdogpolska/imap-to-webhook/blob/master/mails/html_only.eml .

**Comment by fedelemantuano** [comment]
The parsing of `received` is very hard, because it doesn't have a standard. I changed my function. Now it can take more than one regex to parse it. The previous version parsed almost 98% of cases (in my test). Now you can take more field:
 - envelope-sender
 - envelope-from
 - for

I solved with [this commit](https://github.com/SpamScope/mail-parser/commit/e8fcd7a1ab017fdf823cb9bfea9c1bcaa445e9ff).

I can't merge this PR because I tested it with real mail in test.

**Pull request closed without merging**
