### PR TITLE
Add python 3 support

### PR DESCRIPTION
**Pull request by martmists**

### CODE REVIEW

**Comment by fedelemantuano** [comment]
I tried the unittests in `tests/` folder, but they failed with `python3`. Migration to python 3 is in roadmap, but it must follows these steps:

- Make tests
- Test the code with `-3` command-line switch
- Run code through the `2to3` conversion tool
- Run the tests on the new code using Python 3.x

My tests failed so I can't accept this PR.

```
EEEEEE.
======================================================================
ERROR: test_add_content_type (__main__.TestMailParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_mail_parser.py", line 183, in test_add_content_type
    unicode
NameError: name 'unicode' is not defined

======================================================================
ERROR: test_defects_anomalies (__main__.TestMailParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_mail_parser.py", line 144, in test_defects_anomalies
    self.assertIsInstance(parser.parsed_mail_json, unicode)
NameError: name 'unicode' is not defined

======================================================================
ERROR: test_defects_bug (__main__.TestMailParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_mail_parser.py", line 164, in test_defects_bug
    self.assertIsInstance(parser.parsed_mail_json, unicode)
NameError: name 'unicode' is not defined

======================================================================
ERROR: test_parsing_know_values (__main__.TestMailParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_mail_parser.py", line 55, in test_parsing_know_values
    parser.parse_from_file(mail_test_2)
  File "/tmp/mail-parser/tests/../mailparser/__init__.py", line 53, in parse_from_file
    self._message = email.message_from_file(mail)
  File "/usr/lib/python3.5/email/__init__.py", line 54, in message_from_file
    return Parser(*args, **kws).parse(fp)
  File "/usr/lib/python3.5/email/parser.py", line 54, in parse
    data = fp.read(8192)
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 6297: invalid continuation byte

======================================================================
ERROR: test_types (__main__.TestMailParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_mail_parser.py", line 90, in test_types
    parser.parse_from_file(mail_test_2)
  File "/tmp/mail-parser/tests/../mailparser/__init__.py", line 53, in parse_from_file
    self._message = email.message_from_file(mail)
  File "/usr/lib/python3.5/email/__init__.py", line 54, in message_from_file
    return Parser(*args, **kws).parse(fp)
  File "/usr/lib/python3.5/email/parser.py", line 54, in parse
    data = fp.read(8192)
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 6297: invalid continuation byte

======================================================================
ERROR: test_valid_date_mail (__main__.TestMailParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_mail_parser.py", line 47, in test_valid_date_mail
    parser.parse_from_file(mail_test_1),
  File "/tmp/mail-parser/tests/../mailparser/__init__.py", line 54, in parse_from_file
    self._parse()
  File "/tmp/mail-parser/tests/../mailparser/__init__.py", line 209, in _parse
    self._make_mail()
  File "/tmp/mail-parser/tests/../mailparser/__init__.py", line 135, in _make_mail
    "from": self.from_,
  File "/tmp/mail-parser/tests/../mailparser/__init__.py", line 259, in from_
    self._message.get('from')
  File "/tmp/mail-parser/tests/../mailparser/__init__.py", line 74, in _decode_header_part
    output += (i[0] + i[1]).strip()
TypeError: can't concat bytes to str

----------------------------------------------------------------------
Ran 7 tests in 0.025s

FAILED (errors=6)
```

**Comment by martmists** [comment]
I believe `'utf-8' codec can't decode byte 0xec in position 6297: invalid continuation byte` is caused by the fact that the mail contains invalid characters, as shown in this screenshot:



I fixed the testing issues now, and `can't concat bytes to str` should be fixed.

**Comment by fedelemantuano** [comment]
Yes, really. Maybe there is another issue that I must solve.

When I get `charset` of the mail I use [get_content_charset](https://docs.python.org/2/library/email.message.html#email.message.Message.get_content_charset) method. But It's not correct. Every mail parts can have different `charset`. Without `charset` we can't decode mail part corretly.

In our example:

```
In [15]: message = email.message_from_file(open("tests/mails/mail_test_2"))

In [16]: print message.get_charset()
None

In [17]: print message.get_charsets()
[None, None, None, 'iso-8859-1', None, None, None, None]

In [18]: for p in message.walk():
    ...:     print p.get_charset()
    ...:     print p.get_content_charset()
    ...:     print("----------------------")
    ...: 
None
None
----------------------
None
None
----------------------
None
None
----------------------
None
iso-8859-1
----------------------
None
None
----------------------
None
None
----------------------
None
None
----------------------
None
None
----------------------
```

That part has `iso-8859-1` charset, but it's also malformed. A lot of spam mail are malformed. So I must correct this bug, but we should provide a mechanism that catch this exception in `python3` like `python2` (`unicode(i[0], errors='ignore')`).

I can accept your PR, but I must revisit it.

But before we move forward I would ask you to squeeze your commits a bit, I would like to get rid of all this commits messages indicating merge with remote branch, they don't provide much info on the history.

If you need a hand doing the squeeze, you can ask or see this nice web https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

Looking forward to get this in.

**Comment by martmists** [comment]
I haven't been able to install git unfortunately, so I'm afraid I won't e able to edit the commit names.

**Comment by fedelemantuano** [comment]
Sorry but I can't accept this PR.

**Comment by martmists** [comment]
Alright, guess I'll only use it personally. Thanks for considering though!

**Pull request closed without merging**
