### PR TITLE
Adding Python 2/3 Compatibility

### PR DESCRIPTION
**Pull request by cezarsantanna**

### CODE REVIEW

**Comment by fedelemantuano** [comment]
Hi @cezarsantanna, I'm checking the PR. My first step is restart unittest. I don't have any problems with python 2.7 but I have a failed with python 3:

```
$ python3 tests/test_mail_parser.py
.F.....
======================================================================
FAIL: test_defects_anomalies (__main__.TestMailParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_mail_parser.py", line 167, in test_defects_anomalies
    self.assertEqual(False, parser.has_defects)
AssertionError: False != True

----------------------------------------------------------------------
Ran 7 tests in 0.106s

FAILED (failures=1)
```

So I'm checking it. 

Migration to python 3 is in roadmap, but it must follows these steps:
- Make tests
- Test the code with `-3` command-line switch
- Run code through the `2to3` conversion tool
- Run the tests on the new code using Python 3.x

**Comment by cezarsantanna** [comment]
NoBoundaryInMultipartDefect this is the defect that was detect. As far I now this error do not exist in previous version of python and perhaps the mail_test_1 indeed have this defect!

**Comment by fedelemantuano** [comment]
`NoBoundaryInMultipartDefect` is in [Python 2.7](https://docs.python.org/2.7/library/email.errors.html) and [Python 3.6](https://docs.python.org/3.6/library/email.errors.html), so we have another issue. I will check it.

**Comment by fedelemantuano** [comment]
I'm thinking to use module [six](https://pythonhosted.org/six/) for porting.

**Comment by fedelemantuano** [comment]
In Python 3 there is a new `defect` `CloseBoundaryNotFoundDefect`. The last test fail because with Python this defect is hidden.

**Comment by fedelemantuano** [comment]
I added support to Python 3 with more flexible use of library *six*.

@cezarsantanna @martmists @opsdisk if you want, you can test it and give me a feedback.

**Comment by opsdisk** [comment]
Thanks for the quick update...looks good so far for me.  I'll test it some more this weekend.

**Comment by fedelemantuano** [comment]
I rewrote porting with more flexible **[six](https://pythonhosted.org/six/)**, so I can't accept this PR. Thanks so much for your ideas.

From [release v1.0.0rc1](https://github.com/SpamScope/mail-parser/releases/tag/v1.0.0rc1) mail-parser has Python 2/3 support.

**Pull request closed without merging**
